'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import {
  CanonicalOpportunity,
  MatchAnalysisResult,
  TailoredResumeSuggestions,
  MaterialTone,
} from '@/types/byn';
import {
  ArrowLeft,
  ExternalLink,
  Sparkles,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Copy,
  Check,
  Download,
  Printer,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Globe,
  DollarSign,
  Briefcase,
  FileText,
  Wand2,
  Layers,
  ArrowUpDown,
  Edit3,
  HelpCircle,
  ShieldCheck,
} from 'lucide-react';
import { DidYouApplyModal } from '../feedback/did-you-apply-modal';

interface MatchAnalysisViewProps {
  opportunity: CanonicalOpportunity;
  match: MatchAnalysisResult;
  initialResumeTweaks: TailoredResumeSuggestions;
  initialCoverLetter: string;
  onToneChange?: (tone: MaterialTone) => Promise<string>;
  onRecordFeedback?: (didApply: any, notes?: string) => void;
}

export function MatchAnalysisView({
  opportunity,
  match,
  initialResumeTweaks,
  initialCoverLetter,
  onToneChange,
  onRecordFeedback,
}: MatchAnalysisViewProps) {
  const [activeTone, setActiveTone] = useState<MaterialTone>('confident');
  const [coverLetter, setCoverLetter] = useState(initialCoverLetter);
  const [copiedCoverLetter, setCopiedCoverLetter] = useState(false);
  const [copiedBulletIdx, setCopiedBulletIdx] = useState<number | null>(null);
  const [showApplyFeedbackModal, setShowApplyFeedbackModal] = useState(false);
  const [showCalculationDetails, setShowCalculationDetails] = useState(false);

  const fitScore = match.fitScore;
  const fitBadge = match.fitBadge;

  const handleToneSelect = async (tone: MaterialTone) => {
    setActiveTone(tone);
    if (onToneChange) {
      try {
        const newLetter = await onToneChange(tone);
        setCoverLetter(newLetter);
      } catch (err) {
        console.error('Failed to regenerate tone:', err);
      }
    }
  };

  const copyToClipboard = (text: string, isCoverLetter = false, bulletIdx?: number) => {
    navigator.clipboard.writeText(text);
    if (isCoverLetter) {
      setCopiedCoverLetter(true);
      setTimeout(() => setCopiedCoverLetter(false), 2500);
    } else if (bulletIdx !== undefined) {
      setCopiedBulletIdx(bulletIdx);
      setTimeout(() => setCopiedBulletIdx(null), 2500);
    }
  };

  const downloadTxt = () => {
    const content = `=====================================================
APPLICATION KIT: ${opportunity.title} at ${opportunity.company}
Generated by RemoteMatch (BYN Architecture)
=====================================================

MATCH INTELLIGENCE:
Fit Score: ${fitScore}% (${fitBadge})
Recommendation: ${match.recommendation.toUpperCase()}

WHY THIS JOB:
${match.whyThisJob}

STRENGTHS:
${match.strengths.map((s) => `• ${s}`).join('\n')}

GAPS:
${match.gaps.map((g) => `• ${g}`).join('\n')}

=====================================================
JOB-SPECIFIC RESUME IMPROVEMENTS:
=====================================================
${(match.jobSpecificResumeImprovements || [])
  .map((imp, idx) => `${idx + 1}. ${imp.title}\nRecommendation: ${imp.recommendation}\n`)
  .join('\n')}

=====================================================
TAILORED COVER LETTER (${activeTone.toUpperCase()} TONE):
=====================================================

${coverLetter}

=====================================================
RECOMMENDED RESUME ADJUSTMENTS:
=====================================================

Summary Adjustment:
${initialResumeTweaks.summaryAdjustment}

Recommended Bullets to Emphasize:
${initialResumeTweaks.emphasizeExperience.map((e) => `• ${e}`).join('\n')}

Suggested Bullet Rewrites:
${initialResumeTweaks.bulletRewrites
  .map(
    (b) =>
      `Target: ${b.targetRequirement}\nRewrite: ${b.suggestedRewrite}\n`
  )
  .join('\n')}
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${opportunity.company.replace(/\s+/g, '_')}_Application_Kit.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleOfficialApplyClick = () => {
    window.open(opportunity.officialUrl, '_blank', 'noopener,noreferrer');
    setTimeout(() => {
      setShowApplyFeedbackModal(true);
    }, 1500);
  };

  const recColors = {
    apply: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-400',
    apply_with_caveat: 'border-amber-500/30 bg-amber-500/10 text-amber-400',
    low_priority: 'border-rose-500/30 bg-rose-500/10 text-rose-400',
  };

  const recLabels = {
    apply: 'RECOMMENDATION: APPLY',
    apply_with_caveat: 'RECOMMENDATION: APPLY WITH CAVEAT',
    low_priority: 'RECOMMENDATION: LOW PRIORITY',
  };

  const jobSpecificImprovements = match.jobSpecificResumeImprovements || [];

  return (
    <div className="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6 space-y-8">
      {/* Top Bar: Back & Apply CTA */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-6 border-b border-border no-print">
        <Link
          href="/feed"
          className="flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          <span>Back to Feed</span>
        </Link>

        <div className="flex items-center gap-3 w-full sm:w-auto">
          <button
            onClick={downloadTxt}
            className="flex-1 sm:flex-initial flex items-center justify-center gap-1.5 rounded-xl border border-border bg-secondary px-3.5 py-2 text-xs font-semibold text-foreground hover:bg-secondary/80 transition-colors"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download Kit (.txt)</span>
          </button>

          <button
            onClick={() => window.print()}
            className="hidden sm:flex items-center gap-1.5 rounded-xl border border-border bg-secondary px-3.5 py-2 text-xs font-semibold text-foreground hover:bg-secondary/80 transition-colors"
          >
            <Printer className="h-3.5 w-3.5" />
            <span>Print / PDF</span>
          </button>

          <button
            onClick={handleOfficialApplyClick}
            className="flex-1 sm:flex-initial flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-2.5 text-sm font-bold text-white shadow-lg shadow-emerald-500/20 hover:bg-emerald-600 active:scale-95 transition-all"
          >
            <span>Apply on Official Website</span>
            <ExternalLink className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Hero Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 p-6 rounded-2xl border border-border bg-card shadow-xl">
        <div className="flex items-start gap-4">
          {opportunity.companyLogo ? (
            <img
              src={opportunity.companyLogo}
              alt={opportunity.company}
              className="h-16 w-16 rounded-2xl object-cover border border-border bg-secondary"
            />
          ) : (
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-secondary border border-border text-foreground font-bold text-2xl">
              {opportunity.company.slice(0, 2).toUpperCase()}
            </div>
          )}
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-sm font-semibold text-primary">{opportunity.company}</span>
              <span className="text-xs text-muted-foreground">• {opportunity.remoteType}</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold text-foreground tracking-tight">
              {opportunity.title}
            </h1>
            <div className="flex flex-wrap items-center gap-3 mt-3 text-xs text-muted-foreground">
              <span className="flex items-center gap-1">
                <Globe className="h-3.5 w-3.5 text-emerald-400" />
                {opportunity.remoteType}
              </span>
              <span className="flex items-center gap-1">
                <Briefcase className="h-3.5 w-3.5 text-amber-400" />
                {opportunity.employmentType}
              </span>
              {opportunity.salaryMin && (
                <span className="flex items-center gap-1">
                  <DollarSign className="h-3.5 w-3.5 text-indigo-400" />
                  ${Math.round(opportunity.salaryMin / 1000)}k - ${Math.round((opportunity.salaryMax || 0) / 1000)}k
                </span>
              )}
            </div>
          </div>
        </div>

        {/* Fit Score & Recommendation */}
        <div className="flex flex-row md:flex-col items-center md:items-end justify-between w-full md:w-auto pt-4 md:pt-0 border-t md:border-t-0 border-border">
          <div className="flex items-center gap-3">
            <div className="flex flex-col text-right">
              <span className="text-2xl sm:text-3xl font-black text-foreground">
                {fitScore}%
              </span>
              <span className="text-xs font-semibold text-emerald-400">{fitBadge}</span>
            </div>
          </div>
          <div
            className={`mt-2 rounded-lg border px-3 py-1 text-xs font-bold tracking-wider uppercase ${
              recColors[match.recommendation]
            }`}
          >
            {recLabels[match.recommendation]}
          </div>
          <button
            type="button"
            onClick={() => setShowCalculationDetails(!showCalculationDetails)}
            className="mt-2 inline-flex items-center gap-1 text-[11px] font-semibold text-muted-foreground hover:text-indigo-400 transition-colors"
          >
            <HelpCircle className="h-3 w-3 text-indigo-400" />
            <span>How is this calculated?</span>
            {showCalculationDetails ? (
              <ChevronUp className="h-3 w-3" />
            ) : (
              <ChevronDown className="h-3 w-3" />
            )}
          </button>
        </div>
      </div>

      {/* Expandable Transparent Scoring Model Breakdown */}
      {showCalculationDetails && (
        <div className="p-6 rounded-2xl border border-indigo-500/30 bg-card shadow-xl space-y-5 animate-in fade-in duration-200">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <ShieldCheck className="h-5 w-5 text-emerald-400" />
              <h3 className="font-bold text-sm text-foreground">
                Transparent Multi-Factor Scoring Breakdown ({fitScore}%)
              </h3>
            </div>
            <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground bg-secondary px-2 py-0.5 rounded border border-border">
              Deterministic Gate + Quality
            </span>
          </div>

          <p className="text-xs text-muted-foreground leading-relaxed">
            RemoteMatch evaluates fit by verifying hard eligibility constraints, measuring semantic skill and title alignment, and checking verified candidate evidence.
          </p>

          <div className="space-y-3.5 pt-1">
            {/* 1. Role Alignment */}
            <div className="space-y-1">
              <div className="flex items-center justify-between text-xs">
                <span className="font-medium text-foreground">1. Role & Intent Alignment</span>
                <span className="text-emerald-400 font-semibold">
                  {match.isRoleMatch ? 'Strong Alignment (95%)' : 'Cross-Disciplinary (60%)'}
                </span>
              </div>
              <div className="h-2 w-full rounded-full bg-secondary overflow-hidden">
                <div
                  className="h-full bg-emerald-500 rounded-full transition-all duration-300"
                  style={{ width: match.isRoleMatch ? '95%' : '60%' }}
                />
              </div>
            </div>

            {/* 2. Skill Match */}
            <div className="space-y-1">
              <div className="flex items-center justify-between text-xs">
                <span className="font-medium text-foreground">2. Core Skill & Technology Overlap</span>
                <span className="text-indigo-400 font-semibold">
                  {Math.min(95, Math.max(50, fitScore))}% Stack Match
                </span>
              </div>
              <div className="h-2 w-full rounded-full bg-secondary overflow-hidden">
                <div
                  className="h-full bg-indigo-500 rounded-full transition-all duration-300"
                  style={{ width: `${Math.min(95, Math.max(50, fitScore))}%` }}
                />
              </div>
            </div>

            {/* 3. Seniority Fit */}
            <div className="space-y-1">
              <div className="flex items-center justify-between text-xs">
                <span className="font-medium text-foreground">3. Seniority & Employment Fit</span>
                <span className="text-cyan-400 font-semibold">
                  Matched ({opportunity.employmentType})
                </span>
              </div>
              <div className="h-2 w-full rounded-full bg-secondary overflow-hidden">
                <div
                  className="h-full bg-cyan-500 rounded-full transition-all duration-300"
                  style={{ width: '85%' }}
                />
              </div>
            </div>

            {/* 4. Remote & Legal Gate */}
            <div className="space-y-1">
              <div className="flex items-center justify-between text-xs">
                <span className="font-medium text-foreground">4. Remote & Geographic Eligibility</span>
                <span className="text-emerald-400 font-semibold">
                  {match.isCountryEligible && match.isRemoteEligible
                    ? 'Verified Eligible (Hard Gate Passed)'
                    : 'Geographic Limitations Apply'}
                </span>
              </div>
              <div className="h-2 w-full rounded-full bg-secondary overflow-hidden">
                <div
                  className="h-full bg-emerald-400 rounded-full transition-all duration-300"
                  style={{
                    width: match.isCountryEligible && match.isRemoteEligible ? '100%' : '35%',
                  }}
                />
              </div>
            </div>

            {/* 5. Evidence Quality */}
            <div className="space-y-1">
              <div className="flex items-center justify-between text-xs">
                <span className="font-medium text-foreground">5. Candidate Evidence Quality</span>
                <span className="text-amber-400 font-semibold">
                  {fitScore >= 80 ? 'High (Proven Achievements)' : 'Moderate (Foundational)'}
                </span>
              </div>
              <div className="h-2 w-full rounded-full bg-secondary overflow-hidden">
                <div
                  className="h-full bg-amber-400 rounded-full transition-all duration-300"
                  style={{ width: `${Math.max(65, fitScore - 5)}%` }}
                />
              </div>
            </div>
          </div>

          {/* What could change this score? */}
          <div className="p-4 rounded-xl border border-indigo-500/20 bg-indigo-500/5 space-y-2 text-xs">
            <div className="font-semibold text-indigo-300 flex items-center gap-1.5">
              <Sparkles className="h-3.5 w-3.5" />
              <span>What could change this score?</span>
            </div>
            <ul className="text-muted-foreground space-y-1.5 pl-4 list-disc text-[11px] leading-relaxed">
              <li>
                Resolving unverified skills in your profile increases skill overlap weight by up to +12%.
              </li>
              <li>
                Adding concrete business metrics and architecture ownership in your experience elevates evidence quality.
              </li>
              <li>
                Applying the job-specific resume improvements below directly tailors your application to this employer's priorities.
              </li>
            </ul>
          </div>
        </div>
      )}

      {/* Intelligence Box: "Why You're Seeing This" */}
      <div className="p-6 rounded-2xl border border-indigo-500/30 bg-indigo-950/20 backdrop-blur-sm">
        <div className="flex items-center gap-2 mb-2">
          <Wand2 className="h-4 w-4 text-indigo-400" />
          <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-300">
            Why You're Seeing This
          </h3>
        </div>
        <p className="text-sm text-foreground/90 leading-relaxed">
          {match.whyThisJob}
        </p>
      </div>

      {/* Strengths vs Gaps Breakdown */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        <div className="p-6 rounded-2xl border border-border bg-card shadow-md space-y-4">
          <div className="flex items-center gap-2 text-emerald-400">
            <CheckCircle2 className="h-5 w-5" />
            <h3 className="font-bold text-base text-foreground">Demonstrated Strengths</h3>
          </div>
          <ul className="space-y-2.5 text-sm text-muted-foreground">
            {match.strengths.map((strength, i) => (
              <li key={i} className="flex items-start gap-2.5">
                <span className="text-emerald-400 mt-0.5">✓</span>
                <span className="text-foreground/90">{strength}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Gaps */}
        <div className="p-6 rounded-2xl border border-border bg-card shadow-md space-y-4">
          <div className="flex items-center gap-2 text-amber-400">
            <AlertTriangle className="h-5 w-5" />
            <h3 className="font-bold text-base text-foreground">Identified Gaps</h3>
          </div>
          {match.gaps.length > 0 ? (
            <ul className="space-y-2.5 text-sm text-muted-foreground">
              {match.gaps.map((gap, i) => (
                <li key={i} className="flex items-start gap-2.5">
                  <span className="text-amber-400 mt-0.5">△</span>
                  <span className="text-foreground/90">{gap}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">
              No significant gaps identified. Your background strongly covers all listed criteria.
            </p>
          )}
        </div>
      </div>

      {/* NEW: Job-Specific Resume Analysis (Your Resume vs This Job) */}
      {jobSpecificImprovements.length > 0 && (
        <div className="p-6 rounded-2xl border border-emerald-500/30 bg-emerald-950/15 backdrop-blur-sm space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-emerald-400" />
              <h3 className="font-bold text-base text-foreground">
                Your Resume vs This Opportunity
              </h3>
            </div>
            <span className="text-xs font-semibold text-emerald-400">
              {jobSpecificImprovements.length} Tailoring Improvements Recommended
            </span>
          </div>
          <p className="text-xs text-muted-foreground">
            Connecting your verified onboarding profile directly to {opportunity.company}'s requirements before you apply:
          </p>

          <div className="space-y-3 pt-1">
            {jobSpecificImprovements.map((imp, idx) => (
              <div
                key={idx}
                className="p-4 rounded-xl border border-border bg-card shadow-sm space-y-1.5"
              >
                <div className="flex items-center gap-2">
                  <span className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-500/20 text-emerald-400 font-bold text-xs">
                    {idx + 1}
                  </span>
                  <span className="font-bold text-sm text-foreground">
                    {imp.title}
                  </span>
                </div>
                {imp.currentContext && (
                  <p className="text-xs text-muted-foreground italic pl-7">
                    Context: {imp.currentContext}
                  </p>
                )}
                <p className="text-xs text-foreground/90 leading-relaxed pl-7">
                  {imp.recommendation}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Requirement-by-Requirement Checklist */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-md space-y-4">
        <h3 className="font-bold text-base text-foreground">
          Requirement-by-Requirement Checklist
        </h3>
        <div className="divide-y divide-border/60">
          {match.requirementChecklist.map((item, idx) => (
            <div key={idx} className="py-3 flex items-start justify-between gap-4">
              <div className="space-y-0.5">
                <span className="text-sm font-semibold text-foreground">
                  {item.requirement}
                </span>
                <p className="text-xs text-muted-foreground">{item.note}</p>
              </div>
              <div className="flex-shrink-0">
                {item.status === 'matched' ? (
                  <span className="inline-flex items-center gap-1 rounded-md bg-emerald-500/10 px-2.5 py-1 text-xs font-semibold text-emerald-400 border border-emerald-500/20">
                    <CheckCircle2 className="h-3 w-3" />
                    Matched
                  </span>
                ) : item.status === 'partial' ? (
                  <span className="inline-flex items-center gap-1 rounded-md bg-amber-500/10 px-2.5 py-1 text-xs font-semibold text-amber-400 border border-amber-500/20">
                    <AlertTriangle className="h-3 w-3" />
                    Partial
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1 rounded-md bg-rose-500/10 px-2.5 py-1 text-xs font-semibold text-rose-400 border border-rose-500/20">
                    <XCircle className="h-3 w-3" />
                    Missing
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Application Kit: Tailored Resume Adjustments */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-md space-y-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-indigo-400" />
            <h3 className="font-bold text-base text-foreground">
              Tailored Resume Adjustments
            </h3>
          </div>
          <span className="text-xs text-muted-foreground">High-Signal Recommendations</span>
        </div>

        {/* Summary adjustment tip */}
        <div className="p-4 rounded-xl bg-secondary/50 border border-border space-y-1">
          <span className="text-xs font-semibold text-indigo-400 uppercase tracking-wide">
            Positioning Statement
          </span>
          <p className="text-sm text-foreground/90 leading-relaxed">
            {initialResumeTweaks.summaryAdjustment}
          </p>
        </div>

        {/* Bullets to reorder / emphasize */}
        <div className="space-y-2">
          <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
            Key Achievements to Emphasize
          </span>
          <ul className="space-y-1.5 text-sm">
            {initialResumeTweaks.emphasizeExperience.map((exp, i) => (
              <li key={i} className="flex items-start gap-2 text-foreground/90">
                <span className="text-primary mt-0.5">•</span>
                <span>{exp}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Suggested Bullet Rewrites */}
        <div className="space-y-3 pt-2">
          <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
            Suggested Bullet Rewrites (Targeted to Requirements)
          </span>
          {initialResumeTweaks.bulletRewrites.map((bullet, idx) => (
            <div
              key={idx}
              className="p-4 rounded-xl border border-border bg-secondary/30 space-y-2"
            >
              <div className="flex items-center justify-between text-xs">
                <span className="font-semibold text-indigo-300">
                  Target: {bullet.targetRequirement}
                </span>
                <button
                  type="button"
                  onClick={() => copyToClipboard(bullet.suggestedRewrite, false, idx)}
                  className="flex items-center gap-1 font-medium text-muted-foreground hover:text-foreground transition-colors"
                >
                  {copiedBulletIdx === idx ? (
                    <>
                      <Check className="h-3.5 w-3.5 text-emerald-400" />
                      <span className="text-emerald-400">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="h-3.5 w-3.5" />
                      <span>Copy Bullet</span>
                    </>
                  )}
                </button>
              </div>
              <p className="text-sm text-foreground font-medium leading-relaxed bg-background/50 p-2.5 rounded-lg border border-border/50">
                "{bullet.suggestedRewrite}"
              </p>
              <span className="text-[11px] text-muted-foreground block">
                Original context: {bullet.originalContext}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Application Kit: Tailored Cover Letter / Proposal */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-md space-y-5">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h3 className="font-bold text-base text-foreground">
              Tailored Application Letter / Proposal
            </h3>
            <span className="text-xs text-muted-foreground">
              Concise, job-specific pitch with zero boilerplate
            </span>
          </div>

          {/* Tone Selector */}
          <div className="flex items-center gap-1 rounded-xl bg-secondary p-1 border border-border">
            {(['confident', 'conversational', 'formal'] as MaterialTone[]).map((tone) => (
              <button
                key={tone}
                type="button"
                onClick={() => handleToneSelect(tone)}
                className={`rounded-lg px-3 py-1 text-xs font-semibold capitalize transition-colors ${
                  activeTone === tone
                    ? 'bg-background text-foreground shadow-sm'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                {tone}
              </button>
            ))}
          </div>
        </div>

        {/* Textbox / Display */}
        <div className="relative">
          <textarea
            readOnly
            value={coverLetter}
            rows={12}
            className="w-full rounded-xl border border-border bg-secondary/30 p-4 text-sm leading-relaxed text-foreground font-sans focus:outline-none resize-none"
          />
          <button
            type="button"
            onClick={() => copyToClipboard(coverLetter, true)}
            className="absolute top-3 right-3 flex items-center gap-1.5 rounded-lg bg-secondary/90 backdrop-blur-md px-3 py-1.5 text-xs font-semibold text-foreground border border-border hover:bg-secondary transition-colors"
          >
            {copiedCoverLetter ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-400" />
                <span className="text-emerald-400">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                <span>Copy Letter</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Bottom Sticky-style Final Apply Bar */}
      <div className="p-6 rounded-2xl border border-emerald-500/30 bg-emerald-950/20 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div>
          <h4 className="font-bold text-base text-foreground">
            Ready to submit for {opportunity.company}?
          </h4>
          <p className="text-xs text-muted-foreground mt-0.5">
            Your materials are ready. Apply on the official website, then confirm your application.
          </p>
        </div>
        <button
          type="button"
          onClick={handleOfficialApplyClick}
          className="w-full sm:w-auto flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white shadow-xl shadow-emerald-500/25 hover:bg-emerald-600 transition-all active:scale-95"
        >
          <span>Apply on Official Website</span>
          <ExternalLink className="h-4 w-4" />
        </button>
      </div>

      {/* Post-Apply Outcome Feedback Modal */}
      <DidYouApplyModal
        isOpen={showApplyFeedbackModal}
        companyName={opportunity.company}
        onClose={() => setShowApplyFeedbackModal(false)}
        onSubmitFeedback={(didApply, notes) => {
          setShowApplyFeedbackModal(false);
          if (onRecordFeedback) {
            onRecordFeedback(didApply, notes);
          }
        }}
      />
    </div>
  );
}
