import Link from "next/link";
import { ArrowRight, Check, CircleCheck, MapPin, BriefcaseBusiness } from "lucide-react";

export default function Home(){return <main className="page">
 <section className="container grid items-center gap-14 py-16 lg:grid-cols-[1fr_470px] lg:py-24">
  <div><span className="status good">Decision-first job search</span><h1 className="mt-6 max-w-2xl text-5xl font-semibold tracking-[-.04em] sm:text-6xl">Know your chances before you apply.</h1><p className="mt-6 max-w-xl text-lg leading-8 muted">See which opportunities fit your experience, what is missing, and what to improve before you spend time applying.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/onboarding" className="soft-button primary inline-flex items-center justify-center gap-2">Upload resume <ArrowRight size={17}/></Link><Link href="/feed" className="soft-button secondary inline-flex items-center justify-center">Explore opportunities</Link></div><div className="mt-7 flex flex-wrap gap-4 text-sm muted"><span className="flex items-center gap-2"><CircleCheck size={16} className="text-[#087f70]"/> Evidence grounded</span><span className="flex items-center gap-2"><CircleCheck size={16} className="text-[#087f70]"/> Eligibility checked</span><span className="flex items-center gap-2"><CircleCheck size={16} className="text-[#087f70]"/> Official apply links</span></div></div>
  <div className="soft-card soft-hover p-5"><div className="flex items-start justify-between"><div><div className="grid size-11 place-items-center rounded-xl bg-[#f0f1ef] font-semibold">L</div><p className="mt-4 text-sm muted">Linear</p><h2 className="text-xl font-semibold">Senior Product Designer</h2><div className="mt-2 flex flex-wrap gap-3 text-sm muted"><span className="flex items-center gap-1"><MapPin size={14}/>Remote · Worldwide</span><span>$140k–$180k</span></div></div><div className="rounded-2xl bg-[#e6f4f1] px-3 py-2 text-center"><div className="mono text-2xl font-bold text-[#087f70]">92</div><div className="text-[11px] font-semibold text-[#4c6f6a]">Strong fit</div></div></div><div className="mt-6 grid gap-2.5 rounded-2xl bg-[#f7f7f5] p-4 text-sm"><div className="flex items-center gap-2"><Check size={16} className="text-[#087f70]"/>Role alignment</div><div className="flex items-center gap-2"><Check size={16} className="text-[#087f70]"/>Relevant experience</div><div className="flex items-center gap-2"><Check size={16} className="text-[#087f70]"/>Location eligible</div><div className="flex items-center gap-2"><Check size={16} className="text-[#087f70]"/>Core skills demonstrated</div></div><div className="mt-4 rounded-2xl bg-[#fff4d8] p-4 text-sm"><p className="font-semibold text-[#805500]">1 thing to strengthen</p><p className="mt-1 text-[#765f32]">Systems-design impact is not clearly demonstrated.</p></div><Link href="/match/1" className="mt-4 flex items-center justify-between rounded-xl border border-[#e7e7e3] px-4 py-3 text-sm font-semibold">View match <ArrowRight size={16}/></Link></div>
 </section>
 <section className="border-y border-[#e7e7e3] bg-white"><div className="container py-14"><div className="grid gap-3 sm:grid-cols-4">{[['01','Discover','Find relevant opportunities'],['02','Understand','See why you match'],['03','Decide','Know what is missing'],['04','Apply','Strengthen and submit']].map(([n,t,d])=><div key={n} className="rounded-2xl bg-[#fafaf9] p-5"><span className="mono text-xs text-[#087f70]">{n}</span><h3 className="mt-8 font-semibold">{t}</h3><p className="mt-1 text-sm leading-6 muted">{d}</p></div>)}</div></div></section>
 <section className="container py-16"><div className="soft-card p-7 lg:p-10"><div className="grid gap-10 lg:grid-cols-[1fr_360px] lg:items-center"><div><p className="text-sm font-semibold text-[#087f70]">Built around better decisions</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight">The score is useful because you can see the evidence behind it.</h2><p className="mt-4 max-w-2xl leading-7 muted">BYN separates eligibility, fit, evidence and gaps so you can decide whether an opportunity deserves your time.</p></div><div className="grid gap-3">{['Clear eligibility','Evidence behind recommendations','Outcome tracking'].map(x=><div className="flex items-center gap-3 rounded-2xl bg-[#f6f6f4] p-4 text-sm" key={x}><CircleCheck size={18} className="text-[#087f70]"/>{x}</div>)}</div></div></div></section>
 </main>}
