/**
 * RemoteMatch — 500-Company Expansion Cohort Dataset
 * ==============================================================================
 * Curated cohort of 500 remote-first/remote-friendly technology employers
 * across 5 primary high-yield engineering sectors:
 * 1. AI / ML & GenAI Tooling (100 companies)
 * 2. Cloud Infrastructure, DevOps & Observability (100 companies)
 * 3. Data Engineering, Analytics & Modern Databases (100 companies)
 * 4. Cybersecurity, Identity & Compliance (100 companies)
 * 5. Modern SaaS, Product Collaboration & Global Fintech (100 companies)
 * ==============================================================================
 */

export interface CohortCompany {
  name: string;
  domain: string;
  industry: string;
}

export const COHORT_500: CohortCompany[] = [
  // ============================================================================
  // 1. AI / ML & GenAI Tooling (100 companies)
  // ============================================================================
  { name: 'OpenAI', domain: 'openai.com', industry: 'ai_research' },
  { name: 'Anthropic', domain: 'anthropic.com', industry: 'ai_safety' },
  { name: 'Hugging Face', domain: 'huggingface.co', industry: 'ai_community' },
  { name: 'Cohere', domain: 'cohere.com', industry: 'nlp_ai' },
  { name: 'Scale AI', domain: 'scale.com', industry: 'data_annotation' },
  { name: 'Runway', domain: 'runwayml.com', industry: 'generative_media' },
  { name: 'Midjourney', domain: 'midjourney.com', industry: 'generative_media' },
  { name: 'Perplexity', domain: 'perplexity.ai', industry: 'ai_search' },
  { name: 'LangChain', domain: 'langchain.com', industry: 'ai_orchestration' },
  { name: 'LlamaIndex', domain: 'llamaindex.ai', industry: 'ai_data_framework' },
  { name: 'Deepset', domain: 'deepset.ai', industry: 'llm_framework' },
  { name: 'Anyscale', domain: 'anyscale.com', industry: 'distributed_compute' },
  { name: 'Modal', domain: 'modal.com', industry: 'cloud_compute' },
  { name: 'RunPod', domain: 'runpod.io', industry: 'gpu_cloud' },
  { name: 'Together AI', domain: 'together.ai', industry: 'cloud_ai' },
  { name: 'Cerebras', domain: 'cerebras.net', industry: 'ai_hardware' },
  { name: 'Groq', domain: 'groq.com', industry: 'ai_inference' },
  { name: 'Character.ai', domain: 'character.ai', industry: 'conversational_ai' },
  { name: 'Synthesia', domain: 'synthesia.io', industry: 'ai_video' },
  { name: 'HeyGen', domain: 'heygen.com', industry: 'ai_video' },
  { name: 'Fireworks AI', domain: 'fireworks.ai', industry: 'ai_inference' },
  { name: 'Baseten', domain: 'baseten.co', industry: 'ml_infrastructure' },
  { name: 'Replicate', domain: 'replicate.com', industry: 'ai_cloud' },
  { name: 'Modular', domain: 'modular.com', industry: 'ai_compiler' },
  { name: 'Cursor', domain: 'cursor.com', industry: 'ai_editor' },
  { name: 'Tabnine', domain: 'tabnine.com', industry: 'ai_coding' },
  { name: 'Codeium', domain: 'codeium.com', industry: 'ai_coding' },
  { name: 'Poolside', domain: 'poolside.ai', industry: 'ai_coding' },
  { name: 'Weights & Biases', domain: 'wandb.ai', industry: 'mlops' },
  { name: 'Comet ML', domain: 'comet.com', industry: 'mlops' },
  { name: 'Neptune AI', domain: 'neptune.ai', industry: 'mlops' },
  { name: 'ClearML', domain: 'clear.ml', industry: 'mlops' },
  { name: 'Labelbox', domain: 'labelbox.com', industry: 'data_labeling' },
  { name: 'Snorkel AI', domain: 'snorkel.ai', industry: 'programmatic_labeling' },
  { name: 'Roboflow', domain: 'roboflow.com', industry: 'computer_vision' },
  { name: 'Voxel51', domain: 'voxel51.com', industry: 'computer_vision' },
  { name: 'Mistral AI', domain: 'mistral.ai', industry: 'open_models' },
  { name: 'Stability AI', domain: 'stability.ai', industry: 'generative_ai' },
  { name: 'ElevenLabs', domain: 'elevenlabs.io', industry: 'voice_ai' },
  { name: 'AssemblyAI', domain: 'assemblyai.com', industry: 'speech_ai' },
  { name: 'Deepgram', domain: 'deepgram.com', industry: 'audio_ai' },
  { name: 'Speechify', domain: 'speechify.com', industry: 'text_to_speech' },
  { name: 'Descript', domain: 'descript.com', industry: 'audio_video_ai' },
  { name: 'Otter.ai', domain: 'otter.ai', industry: 'transcription' },
  { name: 'Rev', domain: 'rev.com', industry: 'speech_to_text' },
  { name: 'Jasper', domain: 'jasper.ai', industry: 'ai_content' },
  { name: 'Copy.ai', domain: 'copy.ai', industry: 'ai_marketing' },
  { name: 'Writer', domain: 'writer.com', industry: 'enterprise_genai' },
  { name: 'Typeface', domain: 'typeface.ai', industry: 'enterprise_content' },
  { name: 'Glean', domain: 'glean.com', industry: 'enterprise_search' },
  { name: 'Hebbia', domain: 'hebbia.ai', industry: 'knowledge_ai' },
  { name: 'Harvey', domain: 'harvey.ai', industry: 'legal_ai' },
  { name: 'EvenUp', domain: 'evenup.com', industry: 'legal_tech_ai' },
  { name: 'Casetext', domain: 'casetext.com', industry: 'legal_ai' },
  { name: 'Abridge', domain: 'abridge.com', industry: 'medical_ai' },
  { name: 'Ambience Healthcare', domain: 'ambiencehealthcare.com', industry: 'medical_ai' },
  { name: 'Suki AI', domain: 'suki.ai', industry: 'healthcare_ai' },
  { name: 'Kindo', domain: 'kindo.ai', industry: 'ai_security' },
  { name: 'Promptfoo', domain: 'promptfoo.dev', industry: 'llm_eval' },
  { name: 'Arize AI', domain: 'arize.com', industry: 'llm_observability' },
  { name: 'Fiddler AI', domain: 'fiddler.ai', industry: 'model_governance' },
  { name: 'WhyLabs', domain: 'whylabs.ai', industry: 'ai_observability' },
  { name: 'TruEra', domain: 'truera.com', industry: 'ai_quality' },
  { name: 'Arthur AI', domain: 'arthur.ai', industry: 'model_monitoring' },
  { name: 'Pachyderm', domain: 'pachyderm.com', industry: 'data_lineage' },
  { name: 'Iterative', domain: 'iterative.ai', industry: 'mldvc' },
  { name: 'DagsHub', domain: 'dagshub.com', industry: 'data_science_collab' },
  { name: 'Saturn Cloud', domain: 'saturncloud.io', industry: 'data_science_platform' },
  { name: 'Lightning AI', domain: 'lightning.ai', industry: 'pytorch_platform' },
  { name: 'Predibase', domain: 'predibase.com', industry: 'low_code_ai' },
  { name: 'OctoML', domain: 'octoml.ai', industry: 'model_optimization' },
  { name: 'CentML', domain: 'centml.ai', industry: 'gpu_optimization' },
  { name: 'Deci AI', domain: 'deci.ai', industry: 'deep_learning' },
  { name: 'Neural Magic', domain: 'neuralmagic.com', industry: 'sparse_inference' },
  { name: 'Coactive AI', domain: 'coactive.ai', industry: 'multimodal_search' },
  { name: 'Twelve Labs', domain: 'twelvelabs.io', industry: 'video_understanding' },
  { name: 'Tavus', domain: 'tavus.io', industry: 'video_generation' },
  { name: 'Luma AI', domain: 'lumalabs.ai', industry: '3d_generative_ai' },
  { name: 'Kaedim', domain: 'kaedim3d.com', industry: '3d_mesh_ai' },
  { name: 'Sloyd', domain: 'sloyd.ai', industry: '3d_generation' },
  { name: 'Scenario', domain: 'scenario.com', industry: 'game_asset_ai' },
  { name: 'Inworld AI', domain: 'inworld.ai', industry: 'npc_ai' },
  { name: 'Photoroom', domain: 'photoroom.com', industry: 'photo_ai' },
  { name: 'Cutout.pro', domain: 'cutout.pro', industry: 'image_processing' },
  { name: 'Magnific AI', domain: 'magnific.ai', industry: 'upscaling_ai' },
  { name: 'Civitai', domain: 'civitai.com', industry: 'model_sharing' },
  { name: 'Leonardo AI', domain: 'leonardo.ai', industry: 'art_generation' },
  { name: 'PlayHT', domain: 'play.ht', industry: 'voice_generation' },
  { name: 'Resemble AI', domain: 'resemble.ai', industry: 'voice_cloning' },
  { name: 'WellSaid Labs', domain: 'wellsaidlabs.com', industry: 'voice_ai' },
  { name: 'Coqui', domain: 'coqui.ai', industry: 'open_speech' },
  { name: 'Symbl.ai', domain: 'symbl.ai', industry: 'conversation_intelligence' },
  { name: 'DeepL', domain: 'deepl.com', industry: 'translation_ai' },
  { name: 'Unbabel', domain: 'unbabel.com', industry: 'ai_translation' },
  { name: 'Lilt', domain: 'lilt.com', industry: 'enterprise_translation' },
  { name: 'Kore.ai', domain: 'kore.ai', industry: 'enterprise_chatbots' },
  { name: 'Cognigy', domain: 'cognigy.com', industry: 'contact_center_ai' },
  { name: 'Ada', domain: 'ada.cx', industry: 'customer_service_ai' },
  { name: 'Forethought', domain: 'forethought.ai', industry: 'support_automation' },
  { name: 'Sierra', domain: 'sierra.ai', industry: 'conversational_agents' },

  // ============================================================================
  // 2. Cloud Infrastructure, DevOps & Observability (100 companies)
  // ============================================================================
  { name: 'GitLab', domain: 'gitlab.com', industry: 'devsecops' },
  { name: 'HashiCorp', domain: 'hashicorp.com', industry: 'infrastructure_cloud' },
  { name: 'Vercel', domain: 'vercel.com', industry: 'frontend_cloud' },
  { name: 'Supabase', domain: 'supabase.com', industry: 'backend_platform' },
  { name: 'Netlify', domain: 'netlify.com', industry: 'cloud_hosting' },
  { name: 'Fly.io', domain: 'fly.io', industry: 'edge_compute' },
  { name: 'Railway', domain: 'railway.app', industry: 'cloud_platform' },
  { name: 'Render', domain: 'render.com', industry: 'cloud_hosting' },
  { name: 'Pulumi', domain: 'pulumi.com', industry: 'infrastructure_code' },
  { name: 'Temporal', domain: 'temporal.io', industry: 'workflow_orchestration' },
  { name: 'Tailscale', domain: 'tailscale.com', industry: 'mesh_vpn' },
  { name: 'Datadog', domain: 'datadoghq.com', industry: 'cloud_observability' },
  { name: 'Grafana Labs', domain: 'grafana.com', industry: 'metrics_visualization' },
  { name: 'Dynatrace', domain: 'dynatrace.com', industry: 'apm_observability' },
  { name: 'New Relic', domain: 'newrelic.com', industry: 'observability_platform' },
  { name: 'Elastic', domain: 'elastic.co', industry: 'search_observability' },
  { name: 'Sentry', domain: 'sentry.io', industry: 'error_monitoring' },
  { name: 'Honeycomb', domain: 'honeycomb.io', industry: 'observability' },
  { name: 'Chronosphere', domain: 'chronosphere.io', industry: 'cloud_native_metrics' },
  { name: 'Better Stack', domain: 'betterstack.com', industry: 'uptime_incident' },
  { name: 'Highlight', domain: 'highlight.io', industry: 'fullstack_observability' },
  { name: 'LogRocket', domain: 'logrocket.com', industry: 'session_replay' },
  { name: 'Bugsnag', domain: 'bugsnag.com', industry: 'stability_monitoring' },
  { name: 'Postman', domain: 'postman.com', industry: 'api_platform' },
  { name: 'Kong', domain: 'konghq.com', industry: 'api_gateway' },
  { name: 'Traefik Labs', domain: 'traefik.io', industry: 'edge_router' },
  { name: 'Envoy Gateway', domain: 'envoyproxy.io', industry: 'service_mesh' },
  { name: 'Solo.io', domain: 'solo.io', industry: 'cloud_networking' },
  { name: 'Buoyant', domain: 'buoyant.io', industry: 'service_mesh' },
  { name: 'Isovalent', domain: 'isovalent.com', industry: 'ebpf_networking' },
  { name: 'Docker', domain: 'docker.com', industry: 'containerization' },
  { name: 'Canonical', domain: 'canonical.com', industry: 'linux_enterprise' },
  { name: 'SUSE', domain: 'suse.com', industry: 'open_source_linux' },
  { name: 'Red Hat', domain: 'redhat.com', industry: 'enterprise_linux' },
  { name: 'Cloudflare', domain: 'cloudflare.com', industry: 'edge_cdn_security' },
  { name: 'Fastly', domain: 'fastly.com', industry: 'edge_cloud' },
  { name: 'Akamai', domain: 'akamai.com', industry: 'content_delivery' },
  { name: 'LaunchDarkly', domain: 'launchdarkly.com', industry: 'feature_flags' },
  { name: 'Split Software', domain: 'split.io', industry: 'feature_management' },
  { name: 'Statsig', domain: 'statsig.com', industry: 'product_experimentation' },
  { name: 'PostHog', domain: 'posthog.com', industry: 'product_analytics' },
  { name: 'Mixpanel', domain: 'mixpanel.com', industry: 'user_analytics' },
  { name: 'Amplitude', domain: 'amplitude.com', industry: 'digital_analytics' },
  { name: 'Heap', domain: 'heap.io', industry: 'behavioral_analytics' },
  { name: 'PagerDuty', domain: 'pagerduty.com', industry: 'incident_response' },
  { name: 'Opsgenie', domain: 'opsgenie.com', industry: 'on_call_alerting' },
  { name: 'Incident.io', domain: 'incident.io', industry: 'incident_management' },
  { name: 'Rootly', domain: 'rootly.com', industry: 'incident_response' },
  { name: 'FireHydrant', domain: 'firehydrant.com', industry: 'incident_platform' },
  { name: 'Spacelift', domain: 'spacelift.io', industry: 'iac_automation' },
  { name: 'env0', domain: 'env0.com', industry: 'iac_management' },
  { name: 'Scalr', domain: 'scalr.com', industry: 'terraform_automation' },
  { name: 'Terraform Cloud', domain: 'terraform.io', industry: 'infrastructure_as_code' },
  { name: 'Gruntwork', domain: 'gruntwork.io', industry: 'iac_library' },
  { name: 'Upbound', domain: 'upbound.io', industry: 'crossplane_control_plane' },
  { name: 'Loft Labs', domain: 'loft.sh', industry: 'kubernetes_virtualization' },
  { name: 'Cast AI', domain: 'cast.ai', industry: 'kubernetes_cost' },
  { name: 'Kubecost', domain: 'kubecost.com', industry: 'finops_monitoring' },
  { name: 'Vantage', domain: 'vantage.sh', industry: 'cloud_cost_management' },
  { name: 'CloudZero', domain: 'cloudzero.com', industry: 'cloud_finops' },
  { name: 'ProsperOps', domain: 'prosperops.com', industry: 'compute_optimization' },
  { name: 'Anodot', domain: 'anodot.com', industry: 'cost_intelligence' },
  { name: 'CircleCI', domain: 'circleci.com', industry: 'continuous_integration' },
  { name: 'Travis CI', domain: 'travis-ci.com', industry: 'ci_cd_cloud' },
  { name: 'Buildkite', domain: 'buildkite.com', industry: 'enterprise_ci' },
  { name: 'Codefresh', domain: 'codefresh.io', industry: 'gitops_ci' },
  { name: 'Harness', domain: 'harness.io', industry: 'software_delivery' },
  { name: 'Octopus Deploy', domain: 'octopus.com', industry: 'deployment_automation' },
  { name: 'Argo CD', domain: 'argo-cd.readthedocs.io', industry: 'gitops_k8s' },
  { name: 'Flux CD', domain: 'fluxcd.io', industry: 'gitops_engine' },
  { name: 'Teleport', domain: 'goteleport.com', industry: 'zero_trust_access' },
  { name: 'StrongDM', domain: 'strongdm.com', industry: 'infrastructure_access' },
  { name: 'Apono', domain: 'apono.io', industry: 'privileged_access' },
  { name: 'Border0', domain: 'border0.com', industry: 'zero_trust_ingress' },
  { name: 'Twingate', domain: 'twingate.com', industry: 'zero_trust_network' },
  { name: 'NetBird', domain: 'netbird.io', industry: 'wireguard_mesh' },
  { name: 'ZeroTier', domain: 'zerotier.com', industry: 'virtual_networking' },
  { name: 'Ngrok', domain: 'ngrok.com', industry: 'secure_tunnels' },
  { name: 'LocalXpose', domain: 'localxpose.io', industry: 'reverse_proxy' },
  { name: 'Inlets', domain: 'inlets.dev', industry: 'tunnel_proxy' },
  { name: 'Resend', domain: 'resend.com', industry: 'developer_email' },
  { name: 'Postmark', domain: 'postmarkapp.com', industry: 'transactional_email' },
  { name: 'Mailgun', domain: 'mailgun.com', industry: 'email_api' },
  { name: 'SendGrid', domain: 'sendgrid.com', industry: 'email_delivery' },
  { name: 'Courier', domain: 'courier.com', industry: 'notification_api' },
  { name: 'Novu', domain: 'novu.co', industry: 'open_notifications' },
  { name: 'Knock', domain: 'knock.app', industry: 'notification_infrastructure' },
  { name: 'MagicBell', domain: 'magicbell.com', industry: 'notification_inbox' },
  { name: 'Svix', domain: 'svix.com', industry: 'webhooks_as_a_service' },
  { name: 'Hookdeck', domain: 'hookdeck.com', industry: 'webhook_infrastructure' },
  { name: 'Convoy', domain: 'getconvoy.io', industry: 'webhook_gateway' },
  { name: 'Inngest', domain: 'inngest.com', industry: 'serverless_queues' },
  { name: 'Trigger.dev', domain: 'trigger.dev', industry: 'background_jobs' },
  { name: 'Defer', domain: 'defer.run', industry: 'background_tasks' },
  { name: 'Quirrel', domain: 'quirrel.dev', industry: 'job_queues' },
  { name: 'Zeabur', domain: 'zeabur.com', industry: 'container_cloud' },
  { name: 'Koyeb', domain: 'koyeb.com', industry: 'serverless_engines' },
  { name: 'Northflank', domain: 'northflank.com', industry: 'microservice_cloud' },
  { name: 'Flightcontrol', domain: 'flightcontrol.dev', industry: 'aws_paas' },
  { name: 'Porter', domain: 'porter.run', industry: 'k8s_paas' },

  // ============================================================================
  // 3. Data Engineering, Analytics & Modern Databases (100 companies)
  // ============================================================================
  { name: 'Snowflake', domain: 'snowflake.com', industry: 'data_cloud' },
  { name: 'Databricks', domain: 'databricks.com', industry: 'data_lakehouse' },
  { name: 'ClickHouse', domain: 'clickhouse.com', industry: 'columnar_database' },
  { name: 'Confluent', domain: 'confluent.io', industry: 'kafka_streaming' },
  { name: 'dbt Labs', domain: 'getdbt.com', industry: 'analytics_engineering' },
  { name: 'Fivetran', domain: 'fivetran.com', industry: 'data_integration' },
  { name: 'Starburst', domain: 'starburst.io', industry: 'trino_sql' },
  { name: 'Hex', domain: 'hex.tech', industry: 'collaborative_data' },
  { name: 'Omni', domain: 'omni.co', industry: 'modern_bi' },
  { name: 'MotherDuck', domain: 'motherduck.com', industry: 'duckdb_cloud' },
  { name: 'DuckDB Labs', domain: 'duckdblabs.com', industry: 'embedded_olap' },
  { name: 'Cube', domain: 'cube.dev', industry: 'semantic_layer' },
  { name: 'Preset', domain: 'preset.io', industry: 'superset_cloud' },
  { name: 'Dagster Labs', domain: 'dagster.io', industry: 'data_orchestration' },
  { name: 'Prefect', domain: 'prefect.io', industry: 'workflow_coordination' },
  { name: 'Astronomer', domain: 'astronomer.io', industry: 'managed_airflow' },
  { name: 'Airbyte', domain: 'airbyte.com', industry: 'open_data_sync' },
  { name: 'Meltano', domain: 'meltano.com', industry: 'dataops_platform' },
  { name: 'Monte Carlo', domain: 'montecarlodata.com', industry: 'data_observability' },
  { name: 'Soda', domain: 'soda.io', industry: 'data_testing' },
  { name: 'Great Expectations', domain: 'greatexpectations.io', industry: 'data_validation' },
  { name: 'Census', domain: 'getcensus.com', industry: 'reverse_etl' },
  { name: 'Hightouch', domain: 'hightouch.com', industry: 'reverse_etl' },
  { name: 'RudderStack', domain: 'rudderstack.com', industry: 'customer_data_platform' },
  { name: 'SingleStore', domain: 'singlestore.com', industry: 'distributed_sql' },
  { name: 'Timescale', domain: 'timescale.com', industry: 'time_series_postgres' },
  { name: 'ScyllaDB', domain: 'scylladb.com', industry: 'nosql_database' },
  { name: 'Yugabyte', domain: 'yugabyte.com', industry: 'distributed_postgres' },
  { name: 'Cockroach Labs', domain: 'cockroachlabs.com', industry: 'distributed_sql' },
  { name: 'PlanetScale', domain: 'planetscale.com', industry: 'serverless_mysql' },
  { name: 'Neon', domain: 'neon.tech', industry: 'serverless_postgres' },
  { name: 'Upstash', domain: 'upstash.com', industry: 'serverless_redis' },
  { name: 'Turso', domain: 'turso.tech', industry: 'edge_sqlite' },
  { name: 'Pinecone', domain: 'pinecone.io', industry: 'vector_search' },
  { name: 'Weaviate', domain: 'weaviate.io', industry: 'vector_database' },
  { name: 'Qdrant', domain: 'qdrant.tech', industry: 'vector_engine' },
  { name: 'Chroma', domain: 'trychroma.com', industry: 'ai_database' },
  { name: 'Zilliz', domain: 'zilliz.com', industry: 'vector_data' },
  { name: 'MongoDB', domain: 'mongodb.com', industry: 'document_database' },
  { name: 'Redis', domain: 'redis.io', industry: 'in_memory_data' },
  { name: 'Neo4j', domain: 'neo4j.com', industry: 'graph_database' },
  { name: 'Memgraph', domain: 'memgraph.com', industry: 'in_memory_graph' },
  { name: 'TigerGraph', domain: 'tigergraph.com', industry: 'graph_analytics' },
  { name: 'Dgraph', domain: 'dgraph.io', industry: 'graphql_database' },
  { name: 'Fauna', domain: 'fauna.com', industry: 'document_relational' },
  { name: 'SurrealDB', domain: 'surrealdb.com', industry: 'multi_model_db' },
  { name: 'EdgeDB', domain: 'edgedb.com', industry: 'graph_relational_db' },
  { name: 'Prisma', domain: 'prisma.io', industry: 'database_toolkit' },
  { name: 'Drizzle ORM', domain: 'orm.drizzle.team', industry: 'typescript_orm' },
  { name: 'Hasura', domain: 'hasura.io', industry: 'graphql_engine' },
  { name: 'PostGraphile', domain: 'graphile.org', industry: 'postgres_graphql' },
  { name: 'Bytebase', domain: 'bytebase.com', industry: 'database_ci_cd' },
  { name: 'Liquibase', domain: 'liquibase.com', industry: 'database_migration' },
  { name: 'Flyway', domain: 'flywaydb.org', industry: 'db_versioning' },
  { name: 'ReadySet', domain: 'readyset.io', industry: 'sql_cache' },
  { name: 'PolyScale', domain: 'polyscale.ai', industry: 'ai_sql_cache' },
  { name: 'Momento', domain: 'gomomento.com', industry: 'serverless_cache' },
  { name: 'Stately', domain: 'stately.ai', industry: 'state_machines' },
  { name: 'Tinybird', domain: 'tinybird.co', industry: 'realtime_data_api' },
  { name: 'Rockset', domain: 'rockset.com', industry: 'search_analytics' },
  { name: 'Hydra', domain: 'hydra.so', industry: 'postgres_warehouse' },
  { name: 'ParadeDB', domain: 'paradedb.com', industry: 'postgres_search' },
  { name: 'Lantern', domain: 'lantern.dev', industry: 'postgres_vector' },
  { name: 'pgvector', domain: 'github.com/pgvector', industry: 'postgres_extension' },
  { name: 'DuckDB', domain: 'duckdb.org', industry: 'olap_engine' },
  { name: 'Redpanda', domain: 'redpanda.com', industry: 'streaming_data' },
  { name: 'Decodable', domain: 'decodable.co', industry: 'stream_processing' },
  { name: 'Bytewax', domain: 'bytewax.io', industry: 'python_stream_processing' },
  { name: 'Aiven', domain: 'aiven.io', industry: 'managed_open_source_data' },
  { name: 'Instaclustr', domain: 'instaclustr.com', industry: 'managed_data_infra' },
  { name: 'Tabular', domain: 'tabular.io', industry: 'iceberg_storage' },
  { name: 'Onehouse', domain: 'onehouse.ai', industry: 'managed_lakehouse' },
  { name: 'Dremio', domain: 'dremio.com', industry: 'data_lake_engine' },
  { name: 'Starburst Data', domain: 'starburstdata.com', industry: 'trino_analytics' },
  { name: 'Ahana', domain: 'ahana.io', industry: 'prestodb_cloud' },
  { name: 'Immuta', domain: 'immuta.com', industry: 'data_security_governance' },
  { name: 'Privacera', domain: 'privacera.com', industry: 'data_access_governance' },
  { name: 'Alation', domain: 'alation.com', industry: 'data_catalog' },
  { name: 'Collibra', domain: 'collibra.com', industry: 'data_intelligence' },
  { name: 'Atlan', domain: 'atlan.com', industry: 'active_metadata' },
  { name: 'Secoda', domain: 'secoda.co', industry: 'data_workspace' },
  { name: 'CastorDoc', domain: 'castordoc.com', industry: 'data_catalog' },
  { name: 'Metaphor Data', domain: 'metaphor.io', industry: 'metadata_platform' },
  { name: 'Select Star', domain: 'selectstar.com', industry: 'data_discovery' },
  { name: 'Synq', domain: 'synq.io', industry: 'data_reliability' },
  { name: 'Metaplane', domain: 'metaplane.dev', industry: 'data_observability' },
  { name: 'Bigeye', domain: 'bigeye.com', industry: 'data_quality' },
  { name: 'Anomalo', domain: 'anomalo.com', industry: 'data_quality_monitoring' },
  { name: 'Kensu', domain: 'kensu.io', industry: 'data_observability' },
  { name: 'Acceldata', domain: 'acceldata.io', industry: 'dataops_observability' },
  { name: 'Telmai', domain: 'telmai.com', industry: 'realtime_data_observability' },
  { name: 'Validio', domain: 'validio.io', industry: 'deep_data_quality' },
  { name: 'Databand', domain: 'databand.ai', industry: 'data_pipeline_observability' },
  { name: 'Stemma', domain: 'stemma.ai', industry: 'data_catalog_security' },
  { name: 'AcroMeta', domain: 'datahubproject.io', industry: 'metadata_search' },
  { name: 'OpenMetadata', domain: 'open-metadata.org', industry: 'unified_metadata' },
  { name: 'Amundsen', domain: 'amundsen.io', industry: 'data_discovery' },
  { name: 'Kestra', domain: 'kestra.io', industry: 'event_driven_orchestrator' },
  { name: 'Mage', domain: 'mage.ai', industry: 'modern_data_pipeline' },
  { name: 'Windmill', domain: 'windmill.dev', industry: 'developer_workflows' },

  // ============================================================================
  // 4. Cybersecurity, Identity & Compliance (100 companies)
  // ============================================================================
  { name: '1Password', domain: '1password.com', industry: 'password_security' },
  { name: 'Bitwarden', domain: 'bitwarden.com', industry: 'open_security' },
  { name: 'CrowdStrike', domain: 'crowdstrike.com', industry: 'endpoint_security' },
  { name: 'SentinelOne', domain: 'sentinelone.com', industry: 'autonomous_cybersecurity' },
  { name: 'Wiz', domain: 'wiz.io', industry: 'cloud_security' },
  { name: 'Orca Security', domain: 'orcasecurity.io', industry: 'agentless_cloud_security' },
  { name: 'Lacework', domain: 'lacework.com', industry: 'cloud_workload_security' },
  { name: 'Snyk', domain: 'snyk.io', industry: 'developer_security' },
  { name: 'Semgrep', domain: 'semgrep.dev', industry: 'code_analysis_security' },
  { name: 'Chainguard', domain: 'chainguard.dev', industry: 'software_supply_chain' },
  { name: 'GitGuardian', domain: 'gitguardian.com', industry: 'secrets_detection' },
  { name: 'Truffle Security', domain: 'trufflesecurity.com', industry: 'secrets_scanning' },
  { name: 'Socket Security', domain: 'socket.dev', industry: 'open_source_security' },
  { name: 'Aqua Security', domain: 'aquasec.com', industry: 'container_cloud_native' },
  { name: 'Sysdig', domain: 'sysdig.com', industry: 'runtime_security' },
  { name: 'Prisma Cloud', domain: 'paloaltonetworks.com', industry: 'cloud_security' },
  { name: 'Checkmarx', domain: 'checkmarx.com', industry: 'application_security' },
  { name: 'Veracode', domain: 'veracode.com', industry: 'software_security' },
  { name: 'Synopsys', domain: 'synopsys.com', industry: 'electronic_design_security' },
  { name: 'Rapid7', domain: 'rapid7.com', industry: 'vulnerability_management' },
  { name: 'Tenable', domain: 'tenable.com', industry: 'exposure_management' },
  { name: 'Qualys', domain: 'qualys.com', industry: 'cloud_compliance_security' },
  { name: 'HackerOne', domain: 'hackerone.com', industry: 'bug_bounty_platform' },
  { name: 'Bugcrowd', domain: 'bugcrowd.com', industry: 'crowdsourced_security' },
  { name: 'Intigriti', domain: 'intigriti.com', industry: 'ethical_hacking' },
  { name: 'Cobalt', domain: 'cobalt.io', industry: 'pentest_as_a_service' },
  { name: 'Bishop Fox', domain: 'bishopfox.com', industry: 'offensive_security' },
  { name: 'Synack', domain: 'synack.com', industry: 'premier_penetration_testing' },
  { name: 'Okta', domain: 'okta.com', industry: 'enterprise_identity' },
  { name: 'Auth0', domain: 'auth0.com', industry: 'developer_identity' },
  { name: 'Stytch', domain: 'stytch.com', industry: 'passwordless_auth' },
  { name: 'Clerk', domain: 'clerk.com', industry: 'react_authentication' },
  { name: 'WorkOS', domain: 'workos.com', industry: 'enterprise_sso_scim' },
  { name: 'Descope', domain: 'descope.com', industry: 'drag_drop_authentication' },
  { name: 'Ory', domain: 'ory.sh', industry: 'open_source_identity' },
  { name: 'Keycloak', domain: 'keycloak.org', industry: 'iam_platform' },
  { name: 'Frontegg', domain: 'frontegg.com', industry: 'user_management_platform' },
  { name: 'SuperTokens', domain: 'supertokens.com', industry: 'open_source_auth' },
  { name: 'Transmit Security', domain: 'transmitsecurity.com', industry: 'identity_verification' },
  { name: 'Ping Identity', domain: 'pingidentity.com', industry: 'federated_identity' },
  { name: 'ForgeRock', domain: 'forgerock.com', industry: 'digital_identity' },
  { name: 'OneLogin', domain: 'onelogin.com', industry: 'sso_identity' },
  { name: 'Drata', domain: 'drata.com', industry: 'continuous_compliance' },
  { name: 'Vanta', domain: 'vanta.com', industry: 'automated_security_compliance' },
  { name: 'Secureframe', domain: 'secureframe.com', industry: 'compliance_automation' },
  { name: 'Sprinto', domain: 'sprinto.com', industry: 'soc2_iso_compliance' },
  { name: 'AuditBoard', domain: 'auditboard.com', industry: 'risk_compliance' },
  { name: 'LogicGate', domain: 'logicgate.com', industry: 'grc_platform' },
  { name: 'Hyperproof', domain: 'hyperproof.io', industry: 'compliance_operations' },
  { name: 'Anecdotes', domain: 'anecdotes.ai', industry: 'data_driven_compliance' },
  { name: 'Laika', domain: 'heylaika.com', industry: 'compliance_management' },
  { name: 'Thoropass', domain: 'thoropass.com', industry: 'audit_compliance' },
  { name: 'Strike Graph', domain: 'strikegraph.com', industry: 'cybersecurity_audits' },
  { name: 'Zscaler', domain: 'zscaler.com', industry: 'cloud_security_ztna' },
  { name: 'Netskope', domain: 'netskope.com', industry: 'secure_access_service' },
  { name: 'Cato Networks', domain: 'catonetworks.com', industry: 'sase_networking' },
  { name: 'Perimeter 81', domain: 'perimeter81.com', industry: 'converged_network_security' },
  { name: 'NordLayer', domain: 'nordlayer.com', industry: 'business_vpn' },
  { name: 'ExpressVPN', domain: 'expressvpn.com', industry: 'privacy_security' },
  { name: 'Proton', domain: 'proton.me', industry: 'privacy_communications' },
  { name: 'Tutanota', domain: 'tuta.com', industry: 'encrypted_email' },
  { name: 'Mullvad', domain: 'mullvad.net', industry: 'anonymous_vpn' },
  { name: 'Brave', domain: 'brave.com', industry: 'privacy_browser' },
  { name: 'DuckDuckGo', domain: 'duckduckgo.com', industry: 'privacy_search' },
  { name: 'Tor Project', domain: 'torproject.org', industry: 'anonymity_network' },
  { name: 'Signal', domain: 'signal.org', industry: 'private_messenger' },
  { name: 'Wire', domain: 'wire.com', industry: 'secure_collaboration' },
  { name: 'Element', domain: 'element.io', industry: 'matrix_decentralized' },
  { name: 'Mattermost', domain: 'mattermost.com', industry: 'secure_collaboration' },
  { name: 'Abnormal Security', domain: 'abnormalsecurity.com', industry: 'ai_email_security' },
  { name: 'Tessian', domain: 'tessian.com', industry: 'email_data_loss' },
  { name: 'Ironscales', domain: 'ironscales.com', industry: 'anti_phishing' },
  { name: 'KnowBe4', domain: 'knowbe4.com', industry: 'security_awareness' },
  { name: 'Cofense', domain: 'cofense.com', industry: 'phishing_detection' },
  { name: 'Proofpoint', domain: 'proofpoint.com', industry: 'enterprise_cybersecurity' },
  { name: 'Mimecast', domain: 'mimecast.com', industry: 'email_security_cloud' },
  { name: 'Barracuda Networks', domain: 'barracuda.com', industry: 'network_storage_security' },
  { name: 'Sophos', domain: 'sophos.com', industry: 'next_gen_cybersecurity' },
  { name: 'Trend Micro', domain: 'trendmicro.com', industry: 'global_cybersecurity' },
  { name: 'ESET', domain: 'eset.com', industry: 'threat_prevention' },
  { name: 'Malwarebytes', domain: 'malwarebytes.com', industry: 'anti_malware' },
  { name: 'Kaspersky', domain: 'kaspersky.com', industry: 'security_solutions' },
  { name: 'Bitdefender', domain: 'bitdefender.com', industry: 'endpoint_defense' },
  { name: 'Avast', domain: 'avast.com', industry: 'digital_security' },
  { name: 'Kasada', domain: 'kasada.io', industry: 'bot_protection' },
  { name: 'HUMAN Security', domain: 'humansecurity.com', industry: 'bot_mitigation' },
  { name: 'Arkose Labs', domain: 'arkoselabs.com', industry: 'fraud_prevention' },
  { name: 'DataDome', domain: 'datadome.co', industry: 'bot_protection_waf' },
  { name: 'PerimeterX', domain: 'perimeterx.com', industry: 'web_application_security' },
  { name: 'Cheq', domain: 'cheq.ai', industry: 'go_to_market_security' },
  { name: 'Sift', domain: 'sift.com', industry: 'digital_trust_safety' },
  { name: 'Forter', domain: 'forter.com', industry: 'e_commerce_fraud' },
  { name: 'Riskified', domain: 'riskified.com', industry: 'ecommerce_risk' },
  { name: 'Signifyd', domain: 'signifyd.com', industry: 'commerce_protection' },
  { name: 'Kount', domain: 'kount.com', industry: 'identity_trust' },
  { name: 'Persona', domain: 'withpersona.com', industry: 'identity_verification' },
  { name: 'Veriff', domain: 'veriff.com', industry: 'online_id_verification' },
  { name: 'Jumio', domain: 'jumio.com', industry: 'automated_identity' },
  { name: 'Trulioo', domain: 'trulioo.com', industry: 'global_identity_proof' },
  { name: 'Socure', domain: 'socure.com', industry: 'digital_identity_trust' },

  // ============================================================================
  // 5. Modern SaaS, Product Collaboration & Global Fintech (100 companies)
  // ============================================================================
  { name: 'Stripe', domain: 'stripe.com', industry: 'financial_infrastructure' },
  { name: 'Plaid', domain: 'plaid.com', industry: 'open_banking' },
  { name: 'Brex', domain: 'brex.com', industry: 'corporate_card' },
  { name: 'Ramp', domain: 'ramp.com', industry: 'spend_management' },
  { name: 'Mercury', domain: 'mercury.com', industry: 'startup_banking' },
  { name: 'Adyen', domain: 'adyen.com', industry: 'global_payment_engine' },
  { name: 'Wise', domain: 'wise.com', industry: 'international_money' },
  { name: 'Revolut', domain: 'revolut.com', industry: 'global_financial_app' },
  { name: 'Monzo', domain: 'monzo.com', industry: 'digital_challenger_bank' },
  { name: 'N26', domain: 'n26.com', industry: 'mobile_banking_europe' },
  { name: 'Starling Bank', domain: 'starlingbank.com', industry: 'app_based_banking' },
  { name: 'Chime', domain: 'chime.com', industry: 'consumer_fintech' },
  { name: 'Current', domain: 'current.com', industry: 'mobile_banking_us' },
  { name: 'Varo Bank', domain: 'varomoney.com', industry: 'chartered_digital_bank' },
  { name: 'Qonto', domain: 'qonto.com', industry: 'business_finance_europe' },
  { name: 'Tide', domain: 'tide.co', industry: 'sme_banking' },
  { name: 'Kroo', domain: 'kroo.com', industry: 'neobank_uk' },
  { name: 'Remote', domain: 'remote.com', industry: 'employer_of_record' },
  { name: 'Deel', domain: 'deel.com', industry: 'global_compliance_payroll' },
  { name: 'Oyster', domain: 'oysterhr.com', industry: 'distributed_hr_platform' },
  { name: 'Papaya Global', domain: 'papayaglobal.com', industry: 'workforce_management' },
  { name: 'Gusto', domain: 'gusto.com', industry: 'payroll_and_benefits' },
  { name: 'Rippling', domain: 'rippling.com', industry: 'workforce_management_it' },
  { name: 'Justworks', domain: 'justworks.com', industry: 'peo_payroll' },
  { name: 'TriNet', domain: 'trinet.com', industry: 'hr_solutions' },
  { name: 'BambooHR', domain: 'bamboohr.com', industry: 'people_management' },
  { name: 'Workday', domain: 'workday.com', industry: 'enterprise_hcm' },
  { name: 'Carta', domain: 'carta.com', industry: 'equity_cap_table' },
  { name: 'Pulley', domain: 'pulley.com', industry: 'cap_table_management' },
  { name: 'AngelList', domain: 'angellist.com', industry: 'venture_infrastructure' },
  { name: 'Republic', domain: 'republic.com', industry: 'private_investing' },
  { name: 'Seedrs', domain: 'seedrs.com', industry: 'equity_crowdfunding' },
  { name: 'Crowdcube', domain: 'crowdcube.com', industry: 'investment_platform' },
  { name: 'Moonfare', domain: 'moonfare.com', industry: 'private_equity_fintech' },
  { name: 'Secfi', domain: 'secfi.com', industry: 'stock_option_planning' },
  { name: 'Origin', domain: 'useorigin.com', industry: 'employee_financial_wellness' },
  { name: 'Brightside', domain: 'brightside.com', industry: 'financial_care' },
  { name: 'NorthOne', domain: 'northone.com', industry: 'small_business_banking' },
  { name: 'Novo', domain: 'banknovo.com', industry: 'small_business_fintech' },
  { name: 'Bluevine', domain: 'bluevine.com', industry: 'business_banking' },
  { name: 'Linear', domain: 'linear.app', industry: 'project_issue_tracking' },
  { name: 'Notion', domain: 'notion.so', industry: 'connected_workspace' },
  { name: 'Figma', domain: 'figma.com', industry: 'collaborative_interface_design' },
  { name: 'Miro', domain: 'miro.com', industry: 'visual_collaboration_workspace' },
  { name: 'ClickUp', domain: 'clickup.com', industry: 'all_in_one_productivity' },
  { name: 'Raycast', domain: 'raycast.com', industry: 'developer_productivity' },
  { name: 'Retool', domain: 'retool.com', industry: 'internal_tool_builder' },
  { name: 'Webflow', domain: 'webflow.com', industry: 'visual_web_development' },
  { name: 'Framer', domain: 'framer.com', industry: 'interactive_design_publishing' },
  { name: 'Loom', domain: 'loom.com', industry: 'async_video_messaging' },
  { name: 'Pitch', domain: 'pitch.com', industry: 'collaborative_presentations' },
  { name: 'Tome', domain: 'tome.app', industry: 'generative_storytelling' },
  { name: 'Coda', domain: 'coda.io', industry: 'all_in_one_doc' },
  { name: 'Airtable', domain: 'airtable.com', industry: 'connected_apps_platform' },
  { name: 'Asana', domain: 'asana.com', industry: 'work_management' },
  { name: 'Monday.com', domain: 'monday.com', industry: 'work_os' },
  { name: 'Wrike', domain: 'wrike.com', industry: 'enterprise_work_management' },
  { name: 'Smartsheet', domain: 'smartsheet.com', industry: 'work_execution_platform' },
  { name: 'Basecamp', domain: 'basecamp.com', industry: 'remote_project_collab' },
  { name: 'Doist', domain: 'doist.com', industry: 'todoist_twist_productivity' },
  { name: 'Automattic', domain: 'automattic.com', industry: 'wordpress_publishing' },
  { name: 'Ghost', domain: 'ghost.org', industry: 'independent_publishing' },
  { name: 'Substack', domain: 'substack.com', industry: 'newsletter_publishing' },
  { name: 'Medium', domain: 'medium.com', industry: 'open_publishing' },
  { name: 'Buffer', domain: 'buffer.com', industry: 'social_media_management' },
  { name: 'Hootsuite', domain: 'hootsuite.com', industry: 'social_marketing' },
  { name: 'Sprout Social', domain: 'sproutsocial.com', industry: 'social_intelligence' },
  { name: 'Later', domain: 'later.com', industry: 'visual_social_marketing' },
  { name: 'Loomly', domain: 'loomly.com', industry: 'brand_success_platform' },
  { name: 'Zapier', domain: 'zapier.com', industry: 'workflow_automation' },
  { name: 'Make', domain: 'make.com', industry: 'visual_automation_platform' },
  { name: 'Workato', domain: 'workato.com', industry: 'enterprise_integration_automation' },
  { name: 'Tray.io', domain: 'tray.io', industry: 'advanced_workflow_automation' },
  { name: 'Celigo', domain: 'celigo.com', industry: 'ipaas_integration' },
  { name: 'Boomi', domain: 'boomi.com', industry: 'cloud_integration_platform' },
  { name: 'MuleSoft', domain: 'mulesoft.com', industry: 'api_integration_salesforce' },
  { name: 'Intercom', domain: 'intercom.com', industry: 'ai_customer_service' },
  { name: 'Drift', domain: 'drift.com', industry: 'conversational_marketing' },
  { name: 'Gorgias', domain: 'gorgias.com', industry: 'ecommerce_helpdesk' },
  { name: 'Zendesk', domain: 'zendesk.com', industry: 'service_crm' },
  { name: 'Freshworks', domain: 'freshworks.com', industry: 'business_software_suite' },
  { name: 'Front', domain: 'front.com', industry: 'customer_communication_hub' },
  { name: 'Missive', domain: 'missiveapp.com', industry: 'collaborative_email_chat' },
  { name: 'Superhuman', domain: 'superhuman.com', industry: 'fastest_email_experience' },
  { name: 'Spark Mail', domain: 'sparkmailapp.com', industry: 'smart_email' },
  { name: 'Clean Email', domain: 'clean.email', industry: 'inbox_cleaner' },
  { name: 'Canva', domain: 'canva.com', industry: 'visual_communication_platform' },
  { name: 'InVision', domain: 'invisionapp.com', industry: 'digital_product_design' },
  { name: 'Sketch', domain: 'sketch.com', industry: 'mac_design_platform' },
  { name: 'Abstract', domain: 'abstract.com', industry: 'design_version_control' },
  { name: 'Zeplin', domain: 'zeplin.io', industry: 'design_delivery_specs' },
  { name: 'Hotjar', domain: 'hotjar.com', industry: 'behavior_analytics' },
  { name: 'FullStory', domain: 'fullstory.com', industry: 'digital_experience_analytics' },
  { name: 'Contentsquare', domain: 'contentsquare.com', industry: 'experience_analytics' },
  { name: 'Crazy Egg', domain: 'crazyegg.com', industry: 'website_optimization' },
  { name: 'VWO', domain: 'vwo.com', industry: 'ab_testing_experience' },
  { name: 'Optimizely', domain: 'optimizely.com', industry: 'digital_experience_platform' },
  { name: 'Kameleoon', domain: 'kameleoon.com', industry: 'ai_driven_personalization' },
  { name: 'AB Tasty', domain: 'abtasty.com', industry: 'experience_optimization' },
  { name: 'Unbounce', domain: 'unbounce.com', industry: 'conversion_intelligence_landing' },
];
