import { JobProvider, RawJobPayload } from './types';

export const CURATED_JOBS: RawJobPayload[] = [
      {
        sourceId: 'curated-001',
        source: 'curated',
        title: 'Senior Full Stack Engineer',
        company: 'Automattic',
        description: 'We are looking for a Senior Full Stack Engineer experienced with React, TypeScript, Node.js, and distributed database systems. You will work on globally scalable web architectures across WordPress.com and Tumblr. Experience with modern cloud platforms and async remote collaboration is required.',
        sourceUrl: 'https://automattic.com/work-with-us/',
        officialUrl: 'https://automattic.com/work-with-us/senior-full-stack-engineer',
        jobType: 'Full-time',
        locationString: 'Worldwide',
        salaryString: '$120,000 - $160,000 USD',
        salaryMin: 120000,
        salaryMax: 160000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Distributed Systems'],
        publicationDate: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        status: 'UPDATED',
        experienceLevel: '4-6',
      },
      {
        sourceId: 'curated-002',
        source: 'curated',
        title: 'Staff Product Designer',
        company: 'GitLab',
        description: 'GitLab is looking for a Staff Product Designer to lead end-to-end design systems and developer tools UX. You will conduct user research, build scalable Figma UI components, and collaborate across our global async team.',
        sourceUrl: 'https://about.gitlab.com/jobs/apply/',
        officialUrl: 'https://about.gitlab.com/jobs/apply/staff-product-designer',
        jobType: 'Full-time',
        locationString: 'Worldwide',
        salaryString: '$140,000 - $185,000 USD',
        salaryMin: 140000,
        salaryMax: 185000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['Figma', 'Product Design', 'Design Systems', 'User Research', 'SaaS'],
        publicationDate: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        experienceLevel: '7-10',
      },
      {
        sourceId: 'curated-003',
        source: 'curated',
        title: 'Senior Frontend Engineer (React/Next.js)',
        company: 'Vercel',
        description: 'Join Vercel to build the frontend platform for the web. We are looking for an expert in Next.js, React Server Components, TypeScript, and modern web performance optimization (Core Web Vitals).',
        sourceUrl: 'https://vercel.com/careers',
        officialUrl: 'https://vercel.com/careers/senior-frontend-engineer',
        jobType: 'Full-time',
        locationString: 'Worldwide',
        salaryString: '$130,000 - $170,000 USD',
        salaryMin: 130000,
        salaryMax: 170000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Web Performance'],
        publicationDate: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        experienceLevel: '4-6',
      },
      {
        sourceId: 'curated-004',
        source: 'curated',
        title: 'Lead Product Manager - Developer Experience',
        company: 'Supabase',
        description: 'Supabase is hiring a Lead Product Manager to oversee our open-source PostgreSQL developer experience, database dashboard, and API tools. You will work closely with founders, engineers, and community developers worldwide.',
        sourceUrl: 'https://supabase.com/careers',
        officialUrl: 'https://supabase.com/careers/lead-pm-developer-experience',
        jobType: 'Full-time',
        locationString: 'Worldwide',
        salaryString: '$145,000 - $190,000 USD',
        salaryMin: 145000,
        salaryMax: 190000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['Product Management', 'PostgreSQL', 'Developer Tools', 'Open Source', 'Roadmapping'],
        publicationDate: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        experienceLevel: '7-10',
      },
      {
        sourceId: 'curated-005',
        source: 'curated',
        title: 'Senior Backend Engineer (Go/Distributed Systems)',
        company: 'Buffer',
        description: 'Buffer is a pioneer in transparent remote work. We need a Senior Backend Engineer to scale our scheduling queues, microservices in Go, and data streaming pipelines using Kafka and Kubernetes.',
        sourceUrl: 'https://buffer.com/journey',
        officialUrl: 'https://buffer.com/journey/senior-backend-engineer',
        jobType: 'Full-time',
        locationString: 'Worldwide',
        salaryString: '$125,000 - $155,000 USD',
        salaryMin: 125000,
        salaryMax: 155000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['Go', 'Kafka', 'Kubernetes', 'Microservices', 'PostgreSQL'],
        publicationDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
        experienceLevel: '4-6',
      },
      {
        sourceId: 'curated-006',
        source: 'curated',
        title: 'Freelance AI/ML Engineer (LLM Fine-tuning & RAG)',
        company: 'HyperScale AI Lab',
        description: 'We are seeking an experienced freelance AI Engineer on a 6-month renewable contract to design retrieval-augmented generation (RAG) pipelines, evaluate embeddings, and optimize open models with vLLM.',
        sourceUrl: 'https://hyperscale.ai/contracts',
        officialUrl: 'https://hyperscale.ai/contracts/freelance-ai-engineer',
        jobType: 'Contract',
        locationString: 'Worldwide',
        salaryString: '$70 - $110 / hour',
        salaryMin: 70,
        salaryMax: 110,
        salaryCurrency: 'USD',
        salaryPeriod: 'hourly',
        tags: ['Python', 'PyTorch', 'LLMs', 'RAG', 'Vector Databases', 'LangChain'],
        publicationDate: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
        experienceLevel: '4-6',
      },
      {
        sourceId: 'curated-007',
        source: 'curated',
        title: 'Product Marketing Manager (Remote - US/Canada)',
        company: 'Linear',
        description: 'Linear is seeking a Product Marketing Manager based in the US or Canada time zones to craft positioning, launch major features, and drive developer adoption across tech teams.',
        sourceUrl: 'https://linear.app/careers',
        officialUrl: 'https://linear.app/careers/product-marketing-manager',
        jobType: 'Full-time',
        locationString: 'US/Canada Only',
        salaryString: '$130,000 - $165,000 USD',
        salaryMin: 130000,
        salaryMax: 165000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['Product Marketing', 'Copywriting', 'Positioning', 'SaaS', 'Developer Tools'],
        publicationDate: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
        experienceLevel: '4-6',
      },
      {
        sourceId: 'curated-008',
        source: 'curated',
        title: 'Data Engineer (Remote - Europe / UK)',
        company: 'Monzo',
        description: 'Monzo is expanding its European analytics team. We are looking for a Data Engineer skilled in SQL, dbt, Python, and Snowflake to model financial transaction feeds and real-time fraud alerts.',
        sourceUrl: 'https://monzo.com/careers',
        officialUrl: 'https://monzo.com/careers/data-engineer-eu',
        jobType: 'Full-time',
        locationString: 'Europe / UK Only',
        salaryString: '£75,000 - £95,000 GBP',
        salaryMin: 95000,
        salaryMax: 120000,
        salaryCurrency: 'GBP',
        salaryPeriod: 'yearly',
        tags: ['Python', 'SQL', 'dbt', 'Snowflake', 'ETL', 'Fintech'],
        publicationDate: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
        experienceLevel: '4-6',
      },
      {
        sourceId: 'curated-009',
        source: 'curated',
        title: 'Growth & Content Strategist (Freelance/Contract)',
        company: 'Basecamp',
        description: 'Basecamp & 37signals are looking for a sharp content writer and growth strategist to produce thoughtful essays, tactical product guides, and lifecycle communication for ONCE products.',
        sourceUrl: 'https://37signals.com/jobs',
        officialUrl: 'https://37signals.com/jobs/growth-content-strategist',
        jobType: 'Freelance',
        locationString: 'Worldwide',
        salaryString: '$5,000 - $8,000 / month',
        salaryMin: 60000,
        salaryMax: 96000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['Content Marketing', 'Copywriting', 'SEO', 'Email Marketing', 'Brand Strategy'],
        publicationDate: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
        experienceLevel: '2-3',
      },
      {
        sourceId: 'curated-010',
        source: 'curated',
        title: 'Senior DevOps / Cloud Infrastructure Engineer',
        company: 'DuckDuckGo',
        description: 'DuckDuckGo is looking for a Senior DevOps Engineer to maintain our global privacy-first search infrastructure. Strong experience with Linux, Terraform, Nginx, Ansible, and bare-metal orchestration.',
        sourceUrl: 'https://duckduckgo.com/hiring',
        officialUrl: 'https://duckduckgo.com/hiring/senior-devops-engineer',
        jobType: 'Full-time',
        locationString: 'Worldwide',
        salaryString: '$135,000 - $175,000 USD',
        salaryMin: 135000,
        salaryMax: 175000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['Linux', 'Terraform', 'Ansible', 'Kubernetes', 'Networking', 'Security'],
        publicationDate: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
        status: 'ACTIVE',
        experienceLevel: '7-10',
      },
      {
        sourceId: 'curated-closed-001',
        source: 'curated',
        title: 'Senior Site Reliability Engineer (Closed)',
        company: 'CloudArchive',
        description: 'This position was filled and is no longer accepting applications. CloudArchive hired a Senior SRE to oversee cloud infrastructure.',
        sourceUrl: 'https://cloudarchive.example/careers',
        officialUrl: 'https://cloudarchive.example/careers/senior-sre',
        jobType: 'Full-time',
        locationString: 'Worldwide',
        salaryString: '$130,000 - $160,000 USD',
        salaryMin: 130000,
        salaryMax: 160000,
        salaryCurrency: 'USD',
        salaryPeriod: 'yearly',
        tags: ['Kubernetes', 'Linux', 'Go', 'Infrastructure'],
        publicationDate: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
        closedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
        status: 'EXPIRED',
        isPermanentlyRemoved: false,
        experienceLevel: '4-6',
      },
      {
        sourceId: 'curated-removed-001',
        source: 'curated',
        title: 'Legacy Data Architect (Permanently Removed)',
        company: 'OldDataCorp',
        description: 'This listing has been permanently purged and will return 410 Gone.',
        officialUrl: 'https://olddata.example/jobs/archived',
        jobType: 'Full-time',
        publicationDate: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
        closedAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
        status: 'EXPIRED',
        isPermanentlyRemoved: true,
        experienceLevel: '7-10',
      },
    ];

export class CuratedProvider implements JobProvider {
  readonly name = 'Curated Remote Opportunities';
  readonly sourceKey = 'curated';

  async fetchJobs(): Promise<RawJobPayload[]> {
    return Promise.resolve(CURATED_JOBS);
  }
}
